import type { Metadata } from "next";
import { LayoutAdmin } from "@/components/layouts/layout-admin.comp";
import { ChartBarIcon, ListBulletIcon, TableCellsIcon, } from "@heroicons/react/16/solid";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const menu = [{
  text: 'Dashboard',
  href: '/admin/dashboard',
  icon: <ChartBarIcon width={20} height={20} />,
},
{
  text: 'Category',
  href: '/admin/category',
  icon: <ListBulletIcon width={20} height={20} />,
},
{
  text: 'Product',
  href: '/admin/product',
  icon: <TableCellsIcon width={20} height={20} />,
},
]
export default function AdminRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LayoutAdmin menu={menu}>
      {children}
    </LayoutAdmin>
  );
}
