import type { Metadata } from "next";
import { LayoutCustomer } from "@/components/layouts/customerLayout/layout-customer";
import { Container, Toolbar } from "@mui/material";
import { customerMenu } from "@/base/utils/config";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function CommerceRootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <LayoutCustomer menu={customerMenu}>
            <Container>
                <Toolbar sx={{ displayPrint: 'none' }} />
                {children}
            </Container>
        </LayoutCustomer>
    );
}
