import type { Metadata } from "next";
import { LayoutCustomer } from "@/components/layouts/customerLayout/layout-customer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
const menu = [
    { title: 'Sản phẩm handmade', href: '/handmade/all' },
    { title: 'Len sợi', href: '/wool/all' },
    { title: 'Dụng cụ', href: '/tool/all' },
    { title: 'Nguyên phụ liệu', href: '/material/all' },
    // { title: 'Combo', href: '/combo/all' },
    // { title: 'Khuyến mãi', href: '/promotion/all' },
    { title: 'Khác', href: '/other/all' },
]
export default function CommerceRootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <LayoutCustomer menu={menu}>
            {children}
        </LayoutCustomer>
    );
}
