import type { Metadata } from "next";
import { LayoutCustomer } from "@/components/layouts/customerLayout/layout-customer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
const menu = [
    { title: 'Trang chủ', href: '/' },
    { title: 'Sản phẩm', href: '/handmade/all' },
    { title: 'Blog', href: '/blog' },
]
export default function CustomerRootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <LayoutCustomer menu={menu}>
            {children}
        </LayoutCustomer>
    );
}
